# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import comProto_pb2 as comProto__pb2


class commandServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.topCommand = channel.unary_unary(
                '/commandService/topCommand',
                request_serializer=comProto__pb2.commandMessage.SerializeToString,
                response_deserializer=comProto__pb2.commandMessage.FromString,
                )


class commandServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def topCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_commandServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'topCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.topCommand,
                    request_deserializer=comProto__pb2.commandMessage.FromString,
                    response_serializer=comProto__pb2.commandMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'commandService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class commandService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def topCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/commandService/topCommand',
            comProto__pb2.commandMessage.SerializeToString,
            comProto__pb2.commandMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
